# From https://github.com/gudzpoz/luajava/blob/main/.github/workflows/build-natives.yml
# Modified from https://github.com/libgdx/libgdx/blob/master/.github/workflows/build-publish.yml

name: 构建 LuaJIT

on:
  # 自动触发推送事件
  push:
    branches:
      - v2.1
  schedule:
    - cron: '0 0 1 * *'  # 每月1号的定时构建
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 安装交叉编译工具链
        run: |
          sudo apt update
          sudo apt install -y --force-yes gcc g++ linux-libc-dev libc6-dev
          sudo apt install -y --force-yes linux-libc-dev-arm64-cross linux-libc-dev-amd64-cross
          sudo apt install -y --force-yes libstdc++-9-dev-arm64-cross
          sudo apt install -y --force-yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: 构建 LuaJIT
        run: |
          export NDK_HOME=$ANDROID_NDK_LATEST_HOME
          sh build.sh

      - name: 复制头文件
        run: |
          mkdir -p opt/includes
          cp -f src/*.h opt/includes

      - run: echo "DATA=$( date +"%Y-%m-%d" )" >> $GITHUB_ENV

      - name: 压缩文件
        run:  zip -r ${{ env.DATA }}.zip opt

      - name: 显示文件
        run: |
          pwd
          tree -a

      - name: 发布文件
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATA }}
          files: ${{ env.DATA }}.zip
